In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os,time,pickle
from sklearn.model_selection import train_test_split
from tqdm import tqdm

from joblib import dump, load
from utils import data_process, visualize
from utils.utils import train, test, summary, setup_seed
from utils.models import Att_CNN, CNN, TFEQ, CRNN, M_CRNN

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "6"

In [2]:
data = np.load("./data/data_train.npy", allow_pickle=True)
x_train = data.item().get("x_train")
y_train = data.item().get("y_train")
data = np.load("./data/data_test.npy", allow_pickle=True)
x_test = data.item().get("x_test")
y_test = data.item().get("y_test")
x_train=x_train.transpose((0,2,1))
x_test=x_test.transpose((0,2,1))


x_train = torch.from_numpy(x_train).float()
y_train = torch.from_numpy(y_train).long()
x_test = torch.from_numpy(x_test).float()
y_test = torch.from_numpy(y_test).long()
traindata = TensorDataset(x_train, y_train)
testdata = TensorDataset(x_test, y_test)

train_loader = DataLoader(traindata, batch_size=128, shuffle=True)
test_loader = DataLoader(testdata, batch_size=256, shuffle=True)

In [4]:
%%time
setup_seed(42)
model = CRNN().cuda()
# model=TFEQ(channel=3, time_in=200).cuda()
L = []
test_hist = []
optimizer = optim.Adam(model.parameters(), lr=0.001)
for epoch in range(1, 200 + 1):
    start = time.time()
    loss = train(model, train_loader, optimizer, epoch)
    L.append(loss)
    print("time {:.1f} sec:".format(time.time() - start))
    acc = test(model, test_loader)
    test_hist.append(acc)

Train Epoch: 1, Average Loss: 0.3624
time 0.8 sec:
Test set: Average loss: 0.3566, Accuracy: 1837/2070 (88.74%)

Train Epoch: 2, Average Loss: 0.3449
time 0.7 sec:
Test set: Average loss: 0.3334, Accuracy: 1838/2070 (88.79%)

Train Epoch: 3, Average Loss: 0.2573
time 0.7 sec:
Test set: Average loss: 0.2017, Accuracy: 1920/2070 (92.75%)

Train Epoch: 4, Average Loss: 0.1541
time 0.7 sec:
Test set: Average loss: 0.1368, Accuracy: 1977/2070 (95.51%)

Train Epoch: 5, Average Loss: 0.1395
time 0.7 sec:
Test set: Average loss: 0.1194, Accuracy: 1981/2070 (95.70%)

Train Epoch: 6, Average Loss: 0.1212
time 0.7 sec:
Test set: Average loss: 0.1222, Accuracy: 1993/2070 (96.28%)

Train Epoch: 7, Average Loss: 0.1082
time 0.7 sec:
Test set: Average loss: 0.1069, Accuracy: 2002/2070 (96.71%)

Train Epoch: 8, Average Loss: 0.0904
time 0.7 sec:
Test set: Average loss: 0.0943, Accuracy: 2003/2070 (96.76%)

Train Epoch: 9, Average Loss: 0.0806
time 0.7 sec:
Test set: Average loss: 0.0779, Accuracy: 201

Train Epoch: 73, Average Loss: 0.0076
time 0.7 sec:
Test set: Average loss: 0.0123, Accuracy: 2062/2070 (99.61%)

Train Epoch: 74, Average Loss: 0.0074
time 0.7 sec:
Test set: Average loss: 0.0154, Accuracy: 2058/2070 (99.42%)

Train Epoch: 75, Average Loss: 0.0069
time 0.7 sec:
Test set: Average loss: 0.0139, Accuracy: 2059/2070 (99.47%)

Train Epoch: 76, Average Loss: 0.0085
time 0.7 sec:
Test set: Average loss: 0.0132, Accuracy: 2061/2070 (99.57%)

Train Epoch: 77, Average Loss: 0.0068
time 0.7 sec:
Test set: Average loss: 0.0088, Accuracy: 2064/2070 (99.71%)

Train Epoch: 78, Average Loss: 0.0092
time 0.7 sec:
Test set: Average loss: 0.0115, Accuracy: 2061/2070 (99.57%)

Train Epoch: 79, Average Loss: 0.0055
time 0.7 sec:
Test set: Average loss: 0.0123, Accuracy: 2057/2070 (99.37%)

Train Epoch: 80, Average Loss: 0.0066
time 0.7 sec:
Test set: Average loss: 0.0113, Accuracy: 2062/2070 (99.61%)

Train Epoch: 81, Average Loss: 0.0064
time 0.7 sec:
Test set: Average loss: 0.0098, Accu

Train Epoch: 145, Average Loss: 0.0042
time 0.7 sec:
Test set: Average loss: 0.0097, Accuracy: 2063/2070 (99.66%)

Train Epoch: 146, Average Loss: 0.0024
time 0.7 sec:
Test set: Average loss: 0.0116, Accuracy: 2062/2070 (99.61%)

Train Epoch: 147, Average Loss: 0.0027
time 0.7 sec:
Test set: Average loss: 0.0177, Accuracy: 2061/2070 (99.57%)

Train Epoch: 148, Average Loss: 0.0031
time 0.7 sec:
Test set: Average loss: 0.0152, Accuracy: 2063/2070 (99.66%)

Train Epoch: 149, Average Loss: 0.0033
time 0.7 sec:
Test set: Average loss: 0.0191, Accuracy: 2060/2070 (99.52%)

Train Epoch: 150, Average Loss: 0.0026
time 0.7 sec:
Test set: Average loss: 0.0207, Accuracy: 2059/2070 (99.47%)

Train Epoch: 151, Average Loss: 0.0071
time 0.7 sec:
Test set: Average loss: 0.0135, Accuracy: 2061/2070 (99.57%)

Train Epoch: 152, Average Loss: 0.0053
time 0.7 sec:
Test set: Average loss: 0.0192, Accuracy: 2059/2070 (99.47%)

Train Epoch: 153, Average Loss: 0.0048
time 0.7 sec:
Test set: Average loss: 0.0

In [5]:
model.eval()
y_pred = []
out=[]
y_test = []
with torch.no_grad():
    for data, target in test_loader:
        data = data.cuda()
        output = model(data)
        output=F.softmax(output, dim=1)
        pred = output.max(1, keepdim=True)[1]  
        pred = pred.cpu().numpy().squeeze()
        y_pred.append(pred)
        out.append(output.cpu().numpy())
        y_test.append(target.numpy().squeeze())
y_pred=np.hstack(y_pred)
y_test=np.hstack(y_test)
out=np.vstack(out)

summary(y_pred,y_test)

confusion matrix:
 [[1830    3]
 [   7  230]]
Roc score: 0.9844
F1 score: 0.9787
Recall_score: 0.9705
Precision_score: 0.9871
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1833
           1       0.99      0.97      0.98       237

    accuracy                           1.00      2070
   macro avg       0.99      0.98      0.99      2070
weighted avg       1.00      1.00      1.00      2070



In [6]:
torch.save(model, './models/CRNN_d1.pth')

In [6]:
earth=np.where(y_pred==1)[0]
non_earth=np.where(y_pred==0)[0]

p_earth=out[earth,1].squeeze()

p_non_earth=out[non_earth,0].squeeze()

In [7]:
a = np.random.rand(100)
hist,bins = np.histogram(p_earth,bins=10,range=(0,1))
print(hist)
print(bins)


[  0   0   0   0   0   0   2   1   2 232]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [8]:
a = np.random.rand(100)
hist,bins = np.histogram(p_non_earth,bins=10,range=(0,1))
print(hist)
print(bins)

[   0    0    0    0    0    1    1    2    2 1827]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
