In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os,time,pickle
from sklearn.model_selection import train_test_split
from tqdm import tqdm

from joblib import dump, load
from utils import data_process, visualize
from utils.utils import train, test, summary, setup_seed
from utils.TFEQ import TFEQ,TFEQ_Conv,TFEQ_RNN

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "5"

In [2]:
data = np.load("./data_8/data_train.npy", allow_pickle=True)
x_train = data.item().get("x_train")
y_train = data.item().get("y_train")
data = np.load("./data_8/data_test.npy", allow_pickle=True)
x_test = data.item().get("x_test")
y_test = data.item().get("y_test")
x_train = torch.from_numpy(x_train).float()
y_train = torch.from_numpy(y_train).long()
x_test = torch.from_numpy(x_test).float()
y_test = torch.from_numpy(y_test).long()
traindata = TensorDataset(x_train, y_train)
testdata = TensorDataset(x_test, y_test)

train_loader = DataLoader(traindata, batch_size=128, shuffle=True)
test_loader = DataLoader(testdata, batch_size=256, shuffle=True)

In [8]:
data=torch.rand(16,800,3).cuda()
model=TFEQ_RNN(channel=3, time_in=800).cuda()
model(data).shape

torch.Size([16, 2])

In [3]:
%%time
setup_seed(42)
# model = CRNN().cuda()
model=TFEQ(channel=3, time_in=800).cuda()
L = []
test_hist = []
optimizer = optim.Adam(model.parameters(), lr=0.001)
for epoch in range(1, 200 + 1):
    start = time.time()
    loss = train(model, train_loader, optimizer, epoch)
    L.append(loss)
    print("time {:.1f} sec:".format(time.time() - start))
    acc = test(model, test_loader)
    test_hist.append(acc)

Train Epoch: 1, Average Loss: 0.3617
time 2.7 sec:
Test set: Average loss: 0.3506, Accuracy: 1837/2068 (88.83%)

Train Epoch: 2, Average Loss: 0.3485
time 2.7 sec:
Test set: Average loss: 0.3527, Accuracy: 1837/2068 (88.83%)

Train Epoch: 3, Average Loss: 0.3513
time 2.6 sec:
Test set: Average loss: 0.3530, Accuracy: 1837/2068 (88.83%)

Train Epoch: 4, Average Loss: 0.3501
time 2.8 sec:
Test set: Average loss: 0.3570, Accuracy: 1837/2068 (88.83%)

Train Epoch: 5, Average Loss: 0.3497
time 2.7 sec:
Test set: Average loss: 0.3504, Accuracy: 1837/2068 (88.83%)

Train Epoch: 6, Average Loss: 0.3489
time 2.7 sec:
Test set: Average loss: 0.3501, Accuracy: 1837/2068 (88.83%)

Train Epoch: 7, Average Loss: 0.3493
time 2.7 sec:
Test set: Average loss: 0.3500, Accuracy: 1837/2068 (88.83%)

Train Epoch: 8, Average Loss: 0.3488
time 2.7 sec:
Test set: Average loss: 0.3508, Accuracy: 1837/2068 (88.83%)

Train Epoch: 9, Average Loss: 0.3492
time 2.7 sec:
Test set: Average loss: 0.3507, Accuracy: 183

Train Epoch: 73, Average Loss: 0.0340
time 2.7 sec:
Test set: Average loss: 0.0180, Accuracy: 2051/2068 (99.18%)

Train Epoch: 74, Average Loss: 0.0245
time 2.7 sec:
Test set: Average loss: 0.0185, Accuracy: 2053/2068 (99.27%)

Train Epoch: 75, Average Loss: 0.0255
time 2.7 sec:
Test set: Average loss: 0.0169, Accuracy: 2056/2068 (99.42%)

Train Epoch: 76, Average Loss: 0.0228
time 2.7 sec:
Test set: Average loss: 0.0265, Accuracy: 2049/2068 (99.08%)

Train Epoch: 77, Average Loss: 0.0257
time 2.7 sec:
Test set: Average loss: 0.0175, Accuracy: 2055/2068 (99.37%)

Train Epoch: 78, Average Loss: 0.0239
time 2.7 sec:
Test set: Average loss: 0.0198, Accuracy: 2051/2068 (99.18%)

Train Epoch: 79, Average Loss: 0.0276
time 2.7 sec:
Test set: Average loss: 0.0178, Accuracy: 2050/2068 (99.13%)

Train Epoch: 80, Average Loss: 0.0281
time 2.7 sec:
Test set: Average loss: 0.0331, Accuracy: 2047/2068 (98.98%)

Train Epoch: 81, Average Loss: 0.0269
time 2.7 sec:
Test set: Average loss: 0.0209, Accu

Train Epoch: 145, Average Loss: 0.0139
time 2.7 sec:
Test set: Average loss: 0.0190, Accuracy: 2052/2068 (99.23%)

Train Epoch: 146, Average Loss: 0.0204
time 2.7 sec:
Test set: Average loss: 0.0307, Accuracy: 2049/2068 (99.08%)

Train Epoch: 147, Average Loss: 0.0178
time 2.7 sec:
Test set: Average loss: 0.0195, Accuracy: 2050/2068 (99.13%)

Train Epoch: 148, Average Loss: 0.0179
time 2.7 sec:
Test set: Average loss: 0.0199, Accuracy: 2051/2068 (99.18%)

Train Epoch: 149, Average Loss: 0.0177
time 2.7 sec:
Test set: Average loss: 0.0216, Accuracy: 2051/2068 (99.18%)

Train Epoch: 150, Average Loss: 0.0130
time 2.7 sec:
Test set: Average loss: 0.0171, Accuracy: 2055/2068 (99.37%)

Train Epoch: 151, Average Loss: 0.0151
time 2.7 sec:
Test set: Average loss: 0.0190, Accuracy: 2053/2068 (99.27%)

Train Epoch: 152, Average Loss: 0.0168
time 2.7 sec:
Test set: Average loss: 0.0194, Accuracy: 2052/2068 (99.23%)

Train Epoch: 153, Average Loss: 0.0169
time 2.7 sec:
Test set: Average loss: 0.0

In [4]:
model.eval()
y_pred = []
out=[]
y_test = []
with torch.no_grad():
    for data, target in test_loader:
        data = data.cuda()
        output = model(data)
        output=F.softmax(output, dim=1)
        pred = output.max(1, keepdim=True)[1]  
        pred = pred.cpu().numpy().squeeze()
        y_pred.append(pred)
        out.append(output.cpu().numpy())
        y_test.append(target.numpy().squeeze())
y_pred=np.hstack(y_pred)
y_test=np.hstack(y_test)
out=np.vstack(out)

summary(y_pred,y_test)

confusion matrix:
 [[1828    8]
 [   9  223]]
Roc score: 0.9784
F1 score: 0.9633
Recall_score: 0.9612
Precision_score: 0.9654
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1836
           1       0.97      0.96      0.96       232

    accuracy                           0.99      2068
   macro avg       0.98      0.98      0.98      2068
weighted avg       0.99      0.99      0.99      2068



In [6]:
torch.save(model, './models/TFEQ.pth')

In [9]:
earth=np.where(y_pred==1)[0]
non_earth=np.where(y_pred==0)[0]

p_earth=out[earth,1].squeeze()

p_non_earth=out[non_earth,0].squeeze()

In [12]:
a = np.random.rand(100)
hist,bins = np.histogram(p_earth,bins=10,range=(0,1))
print(hist)
print(bins)


[  0   0   0   0   0   1   4   3   9 217]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [13]:
a = np.random.rand(100)
hist,bins = np.histogram(p_non_earth,bins=10,range=(0,1))
print(hist)
print(bins)

[   0    0    0    0    0    6    5    4    5 1816]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
